name: Release

on:
  push:
    tags:
      - "*"

  workflow_dispatch:

env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  verify-image:
    runs-on: ubuntu-latest

    steps:
      - name: Verify Base Image Integrity
        run: gh attestation verify oci://ghcr.io/vanilla-os/desktop:main --owner Vanilla-OS
        env:
          GH_TOKEN: ${{ github.token }}

  release:
    needs: verify-image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Change Tag in Recipe
        run: |
          sed 's/ghcr.io\/vanilla-os\/desktop:dev/ghcr.io\/vanilla-os\/desktop:main/' -i recipe.yml

      - uses: vanilla-os/vib-gh-action@v0.7.4
        with:
          recipe: "recipe.yml"
          plugins: "Vanilla-OS/vib-fsguard:v1.5.3"

      - uses: actions/upload-artifact@v4
        with:
          name: Containerfile
          path: Containerfile

      - name: Create Release

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: gh release create "${{ github.ref_name }}" --generate-notes Containerfile

      - name: Attest Release Files
        id: attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: "Containerfile"
